"""empty message

Revision ID: 704c830c084a
Revises: 
Create Date: 2024-10-13 22:51:40.936825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704c830c084a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_number', sa.String(length=255), nullable=False),
    sa.Column('book_name', sa.String(length=255), nullable=False),
    sa.Column('book_type', sa.String(length=255), nullable=False),
    sa.Column('book_price', sa.Float(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('book_publisher', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('book')
    # ### end Alembic commands ###
